/**
 * Centralized icon slug registry.
 *
 * Catalogue `iconSlug` values are stable public identifiers. When a slug is not
 * present in the installed `simple-icons` package, map it here to an alias slug
 * or a bundled custom icon id (see `custom-brands.generated.ts`).
 */
export const SUBSCRIPTION_ICON_REGISTRY: Record<string, string> = {
  // AI
  openai: "openai",
  anthropic: "anthropic",
  cursor: "cursor",
  google: "google",
  gemini: "google",
  perplexity: "perplexity",
  githubcopilot: "githubcopilot",
  midjourney: "midjourney",
  runway: "runway",
  elevenlabs: "elevenlabs",
  lovable: "lovable",
  windsurf: "windsurf",
  replit: "replit",
  bolt: "bolt",
  characterai: "characterai",
  poe: "poe",
  blackbox: "blackbox",
  mistral: "mistralai",
  jasper: "jasper",
  deepl: "deepl",
  suno: "suno",
  leonardo: "leonardo",
  grammarly: "grammarly",
  otter: "otter",

  // Streaming
  netflix: "netflix",
  amazonprime: "amazonprime",
  primevideo: "amazonprime",
  disneyplus: "disneyplus",
  hotstar: "hotstar",
  jiohotstar: "hotstar",
  sonyliv: "sonyliv",
  zee5: "zee5",
  crunchyroll: "crunchyroll",
  apple: "apple",
  appletv: "apple",
  paramountplus: "paramountplus",
  max: "max",
  hbomax: "hbomax",
  hulu: "hulu",
  youtube: "youtube",
  peacock: "peacock",
  discoveryplus: "discoveryplus",
  mubi: "mubi",
  jiocinema: "jiocinema",
  sling: "sling",
  fubo: "fubo",
  dazn: "dazn",
  espn: "espn",

  // Music
  spotify: "spotify",
  applemusic: "applemusic",
  youtubemusic: "youtube",
  amazonmusic: "amazon",
  jiosaavn: "jiosaavn",
  gaana: "gaana",
  tidal: "tidal",
  soundcloud: "soundcloud",
  deezer: "deezer",
  pandora: "pandora",
  qobuz: "qobuz",

  // Cloud
  googleone: "google",
  icloud: "apple",
  dropbox: "dropbox",
  onedrive: "microsoftonedrive",
  mega: "mega",
  box: "box",
  pcloud: "pcloud",
  backblaze: "backblaze",
  protondrive: "proton",
  sync: "sync",

  // Productivity
  notion: "notion",
  todoist: "todoist",
  evernote: "evernote",
  slack: "slack",
  zoom: "zoom",
  calendly: "calendly",
  microsoft: "microsoft",
  microsoft365: "microsoft",
  googleworkspace: "google",
  trello: "trello",
  asana: "asana",
  clickup: "clickup",
  monday: "monday",
  airtable: "airtable",
  obsidian: "obsidian",
  zapier: "zapier",
  superhuman: "superhuman",
  fantastical: "fantastical",
  roam: "roamresearch",
  bear: "bear",
  things: "things",
  setapp: "setapp",

  // Developer
  github: "github",
  gitlab: "gitlab",
  jetbrains: "jetbrains",
  vercel: "vercel",
  netlify: "netlify",
  railway: "railway",
  render: "render",
  supabase: "supabase",
  firebase: "firebase",
  cloudflare: "cloudflare",
  digitalocean: "digitalocean",
  aws: "amazonwebservices",
  linode: "linode",
  heroku: "heroku",
  sentry: "sentry",
  postman: "postman",
  linear: "linear",
  mongodb: "mongodb",
  docker: "docker",
  npm: "npm",
  raycast: "raycast",
  planetscale: "planetscale",

  // Design
  adobe: "adobe",
  adobelightroom: "adobe",
  adobephotoshop: "adobe",
  canva: "canva",
  figma: "figma",
  framer: "framer",
  capcut: "capcut",
  envato: "envato",
  sketch: "sketch",
  affinity: "affinity",
  procreate: "procreate",
  dribbble: "dribbble",
  webflow: "webflow",
  spline: "spline",

  // Security
  "1password": "1password",
  bitwarden: "bitwarden",
  dashlane: "dashlane",
  nordvpn: "nordvpn",
  surfshark: "surfshark",
  expressvpn: "expressvpn",
  protonvpn: "protonvpn",
  protonmail: "protonmail",
  lastpass: "lastpass",
  norton: "norton",
  mcafee: "mcafee",
  bitdefender: "bitdefender",
  malwarebytes: "malwarebytes",

  // Learning
  udemy: "udemy",
  coursera: "coursera",
  skillshare: "skillshare",
  masterclass: "masterclass",
  brilliant: "brilliant",
  duolingo: "duolingo",
  udacity: "udacity",
  datacamp: "datacamp",
  linkedinlearning: "linkedin",
  khanacademy: "khanacademy",
  pluralsight: "pluralsight",
  codecademy: "codecademy",
  babbel: "babbel",
  rosettastone: "rosettastone",
  quizlet: "quizlet",

  // Fitness
  cultfit: "cultfit",
  healthifyme: "healthifyme",
  myfitnesspal: "myfitnesspal",
  fittr: "fittr",
  strava: "strava",
  nike: "nike",
  peloton: "peloton",
  calm: "calm",
  headspace: "headspace",
  fitbit: "fitbit",
  whoop: "whoop",
  garmin: "garmin",
  oura: "oura",
  flo: "flo",

  // Finance
  tradingview: "tradingview",
  moneycontrol: "moneycontrol",
  tickertape: "tickertape",
  smallcase: "smallcase",
  etmoney: "etmoney",
  indmoney: "indmoney",
  quickbooks: "quickbooks",
  ynab: "ynab",
  morningstar: "morningstar",
  robinhood: "robinhood",
  zerodha: "zerodha",
  groww: "groww",
  coinbase: "coinbase",
  seekingalpha: "seekingalpha",
  empower: "empower",

  // Communication
  telegram: "telegram",
  discord: "discord",
  x: "x",
  linkedin: "linkedin",
  skype: "skype",
  truecaller: "truecaller",
  teams: "microsoftteams",
  snapchat: "snapchat",
  reddit: "reddit",
  tinder: "tinder",
  bumble: "bumble",
  hinge: "hinge",

  // News
  nytimes: "newyorktimes",
  wsj: "wsj",
  economist: "economist",
  washingtonpost: "washingtonpost",
  bloomberg: "bloomberg",
  financialtimes: "financialtimes",
  theguardian: "theguardian",
  medium: "medium",
  substack: "substack",
  athletic: "theathletic",
  applenews: "apple",
  reuters: "reuters",

  // Gaming
  xbox: "xbox",
  playstation: "playstation",
  nintendo: "nintendo",
  ea: "ea",
  ubisoft: "ubisoft",
  nvidia: "nvidia",
  twitch: "twitch",
  applearcade: "applearcade",
  googleplay: "googleplay",
  roblox: "roblox",
  minecraft: "minecraft",

  // Shopping
  walmart: "walmart",
  costco: "costco",
  instacart: "instacart",
  doordash: "doordash",
  uber: "uber",
  lyft: "lyft",
  zomato: "zomato",
  swiggy: "swiggy",
  blinkit: "blinkit",
  flipkart: "flipkart",
  myntra: "myntra",
  etsy: "etsy",

  // Reading
  audible: "audible",
  kindle: "kindle",
  scribd: "scribd",
  blinkist: "blinkist",
  storytel: "storytel",
  patreon: "patreon",
  onlyfans: "onlyfans",

  // Other
  squarespace: "squarespace",
  wix: "wix",
  wordpress: "wordpress",
  shopify: "shopify",
  mailchimp: "mailchimp",
  hubspot: "hubspot",
  salesforce: "salesforce",
  docusign: "docusign",
  appleone: "apple",
};

/** Resolve a catalogue icon slug to its registry target slug. */
export function resolveSubscriptionIconSlug(iconSlug: string): string {
  const normalized = iconSlug.trim().toLowerCase();
  return SUBSCRIPTION_ICON_REGISTRY[normalized] ?? normalized;
}
