import {
  advanceRecurringRunDate,
  addDays,
  buildTransactionFromRecurringTemplate,
  firestorePaths,
  type RecurringTemplate,
} from "@pfos/shared";
import { doc, getDoc, updateDoc, writeBatch } from "firebase/firestore";

import { getFirebaseDb } from "@/lib/firebase/client";
import { sanitizeForFirestore } from "@/lib/firebase/sanitize";
import { verifyTransaction } from "@/lib/transactions/service";

/** After user confirms a SIP pending entry, roll the plan to the next month. */
export async function advanceSipAfterConfirm(
  uid: string,
  templateId: string,
  runDate: string,
): Promise<void> {
  const db = getFirebaseDb();
  if (!db) {
    return;
  }

  const ref = doc(db, firestorePaths.recurringTemplate(uid, templateId));
  const snap = await getDoc(ref);
  if (!snap.exists()) {
    return;
  }

  const template = snap.data() as RecurringTemplate;
  await updateDoc(ref, {
    nextRunDate: advanceRecurringRunDate(runDate, template.frequency),
    snoozedUntil: null,
    updatedAt: new Date().toISOString(),
  });
}

export async function createSipPendingIfNeeded(
  uid: string,
  template: RecurringTemplate,
  runDate: string,
): Promise<boolean> {
  const db = getFirebaseDb();
  if (!db) {
    return false;
  }

  const transactionId = `${template.id}_${runDate}`;
  const existing = await getDoc(doc(db, firestorePaths.transaction(uid, transactionId)));
  if (existing.exists()) {
    return false;
  }

  const batch = writeBatch(db);
  const transaction = {
    ...buildTransactionFromRecurringTemplate(uid, template, runDate, {
      autoGenerated: true,
    }),
    id: transactionId,
    status: "PENDING" as const,
  };

  batch.set(
    doc(db, firestorePaths.transaction(uid, transactionId)),
    sanitizeForFirestore(transaction as unknown as Record<string, unknown>),
  );
  batch.update(doc(db, firestorePaths.recurringTemplate(uid, template.id)), {
    lastGeneratedDate: runDate,
    updatedAt: new Date().toISOString(),
  });

  await batch.commit();
  return true;
}

/** Confirm today's SIP — verifies the pending entry and advances the schedule. */
export async function confirmSipOccurrence(
  uid: string,
  template: RecurringTemplate,
  runDate: string,
): Promise<void> {
  const transactionId = `${template.id}_${runDate}`;
  await verifyTransaction(uid, transactionId);
  await advanceSipAfterConfirm(uid, template.id, runDate);
}

export async function skipSipOccurrence(
  uid: string,
  template: RecurringTemplate,
  runDate: string,
): Promise<void> {
  const db = getFirebaseDb();
  if (!db) {
    throw new Error("Firebase is not configured.");
  }

  const skipped = [...(template.skippedOccurrences ?? []), runDate];
  const batch = writeBatch(db);
  batch.update(doc(db, firestorePaths.recurringTemplate(uid, template.id)), {
    skippedOccurrences: skipped,
    lastGeneratedDate: runDate,
    nextRunDate: advanceRecurringRunDate(runDate, template.frequency),
    snoozedUntil: null,
    updatedAt: new Date().toISOString(),
  });
  await batch.commit();
}

export async function snoozeSipReminder(
  uid: string,
  template: RecurringTemplate,
  untilDate: string,
): Promise<void> {
  const db = getFirebaseDb();
  if (!db) {
    throw new Error("Firebase is not configured.");
  }

  await updateDoc(doc(db, firestorePaths.recurringTemplate(uid, template.id)), {
    snoozedUntil: untilDate,
    updatedAt: new Date().toISOString(),
  });
}

export function defaultSnoozeUntil(today: string): string {
  return addDays(today, 1);
}
