import { applyFormToTransaction } from "../transactions/form";
import type { RecurringTemplate } from "../types/recurring";
import type { Transaction } from "../types/transaction";
import { AUTO_SIP_TRANSACTION_NOTE } from "../sip/display";
import { isSipTemplate } from "../sip/status";

export function buildTransactionFromRecurringTemplate(
  userId: string,
  template: RecurringTemplate,
  runDate: string,
  options?: { autoGenerated?: boolean },
): Transaction {
  const now = new Date().toISOString();
  const baseNotes = template.notes?.trim() ?? "";
  const sipNotes =
    options?.autoGenerated && isSipTemplate(template)
      ? [AUTO_SIP_TRANSACTION_NOTE, baseNotes].filter(Boolean).join("\n")
      : baseNotes;

  const isSip = isSipTemplate(template);
  const status = isSip
    ? "PENDING"
    : template.autoConfirm
      ? "VERIFIED"
      : "PENDING";

  return applyFormToTransaction(
    {
      id: crypto.randomUUID(),
      userId,
      date: runDate,
      type: template.type,
      amount: template.amount,
      fromAccountId: null,
      toAccountId: null,
      categoryId: null,
      subcategoryId: null,
      splits: null,
      merchant: template.merchant?.trim() || template.name,
      notes: sipNotes,
      isGlobalExpense: false,
      linkedTransactionId: null,
      recurringId: template.id,
      source: "RECURRING",
      status: "VERIFIED",
      createdAt: now,
      updatedAt: now,
    },
    {
      type: template.type,
      amount: template.amount,
      date: runDate,
      fromAccountId: template.fromAccountId ?? null,
      toAccountId: template.toAccountId ?? null,
      categoryId: template.categoryId ?? null,
      merchant: template.merchant?.trim() || template.name,
      notes: sipNotes,
      status,
    },
  );
}
